// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtqjwpwndcsgdhzuvpgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cWp3cHduZGNzZ2RoenV2cGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NDAyNzEsImV4cCI6MjA4ODIxNjI3MX0.wSlkZ6uFOSiyo4zXDpV7syG66AIgLK2ybrnTdf2n--E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});